'use client'

import { useI18n } from './i18n-context'
import jsPDF from 'jspdf'

interface Props {
  analysis: any
}

export default function PdfExportButton({ analysis }: Props) {
  const { t, language } = useI18n()
  
  const exportToPdf = async () => {
    try {
      const pdf = new jsPDF('p', 'mm', 'a4')
      
      // A4 dimensions and margins
      const pageWidth = 210 // A4 width in mm
      const pageHeight = 297 // A4 height in mm
      const margin = 20 // 20mm margins on all sides
      const contentWidth = pageWidth - (2 * margin)
      const maxLineWidth = contentWidth
      
      let yPosition = margin
      
      // Helper function to check if we need a new page
      const checkPageBreak = (heightNeeded: number) => {
        if (yPosition + heightNeeded > pageHeight - margin) {
          pdf.addPage()
          yPosition = margin
          return true
        }
        return false
      }
      
      // Helper function to add wrapped text
      const addText = (text: string, fontSize: number, isBold: boolean = false, color: [number, number, number] = [0, 0, 0]) => {
        pdf.setFontSize(fontSize)
        pdf.setFont('helvetica', isBold ? 'bold' : 'normal')
        pdf.setTextColor(color[0], color[1], color[2])
        
        const lines = pdf.splitTextToSize(text, maxLineWidth)
        const lineHeight = fontSize * 0.5
        
        for (let i = 0; i < lines.length; i++) {
          checkPageBreak(lineHeight)
          pdf.text(lines[i], margin, yPosition)
          yPosition += lineHeight
        }
        
        return lines.length * lineHeight
      }
      
      // Helper function to add a horizontal line
      const addLine = (color: [number, number, number] = [229, 231, 235]) => {
        pdf.setDrawColor(color[0], color[1], color[2])
        pdf.setLineWidth(0.5)
        pdf.line(margin, yPosition, pageWidth - margin, yPosition)
        yPosition += 5
      }
      
      // Translate headers
      const getHeader = (key: string) => {
        const headers: any = {
          nl: {
            title: 'Contract Analyse Rapport',
            overallScore: 'Totaalscore',
            type: 'Type',
            summary: 'Samenvatting',
            redFlags: 'Aandachtspunten',
            positivePoints: 'Sterke Punten',
            recommendations: 'Aanbevelingen',
            recommendation: 'Aanbeveling',
            category: 'Categorie',
            severity: 'Ernst',
            explanation: 'Uitleg',
            footer1: 'Gegenereerd door BeforeISign.be Contract Checker',
            footer2: 'Deze analyse is alleen voor educatieve doeleinden en vormt geen juridisch advies.'
          },
          fr: {
            title: 'Rapport d\'Analyse de Contrat',
            overallScore: 'Score Global',
            type: 'Type',
            summary: 'Résumé',
            redFlags: 'Points d\'Attention',
            positivePoints: 'Points Forts',
            recommendations: 'Recommandations',
            recommendation: 'Recommandation',
            category: 'Catégorie',
            severity: 'Gravité',
            explanation: 'Explication',
            footer1: 'Généré par BeforeISign.be Contract Checker',
            footer2: 'Cette analyse est à des fins éducatives uniquement et ne constitue pas un conseil juridique.'
          },
          en: {
            title: 'Contract Analysis Report',
            overallScore: 'Overall Score',
            type: 'Type',
            summary: 'Summary',
            redFlags: 'Points of Attention',
            positivePoints: 'Positive Points',
            recommendations: 'Recommendations',
            recommendation: 'Recommendation',
            category: 'Category',
            severity: 'Severity',
            explanation: 'Explanation',
            footer1: 'Generated by BeforeISign.be Contract Checker',
            footer2: 'This analysis is for educational purposes only and does not constitute legal advice.'
          }
        }
        return headers[language]?.[key] || headers.en[key]
      }
      
      // HEADER
      pdf.setFillColor(249, 115, 22) // Orange
      pdf.rect(margin, yPosition, contentWidth, 15, 'F')
      pdf.setTextColor(255, 255, 255)
      pdf.setFontSize(20)
      pdf.setFont('helvetica', 'bold')
      pdf.text('BeforeISign.be', pageWidth / 2, yPosition + 10, { align: 'center' })
      yPosition += 20
      
      pdf.setTextColor(100, 100, 100)
      pdf.setFontSize(14)
      pdf.setFont('helvetica', 'normal')
      pdf.text(getHeader('title'), pageWidth / 2, yPosition, { align: 'center' })
      yPosition += 10
      
      pdf.setFontSize(10)
      pdf.text(new Date().toLocaleDateString(), pageWidth / 2, yPosition, { align: 'center' })
      yPosition += 10
      
      addLine()
      
      // SCORE BOX
      checkPageBreak(30)
      pdf.setFillColor(249, 115, 22)
      pdf.roundedRect(margin, yPosition, contentWidth, 25, 3, 3, 'F')
      
      pdf.setTextColor(255, 255, 255)
      pdf.setFontSize(32)
      pdf.setFont('helvetica', 'bold')
      pdf.text(`${(analysis.overallScore / 10).toFixed(1)}/10`, pageWidth / 2, yPosition + 12, { align: 'center' })
      
      pdf.setFontSize(12)
      pdf.setFont('helvetica', 'normal')
      pdf.text(getHeader('overallScore'), pageWidth / 2, yPosition + 20, { align: 'center' })
      yPosition += 30
      
      // CONTRACT TYPE
      if (analysis.contractType) {
        checkPageBreak(10)
        pdf.setTextColor(249, 115, 22)
        pdf.setFontSize(11)
        pdf.setFont('helvetica', 'bold')
        pdf.text(`${getHeader('type')}: `, margin, yPosition)
        
        pdf.setTextColor(0, 0, 0)
        pdf.setFont('helvetica', 'normal')
        const typeWidth = pdf.getTextWidth(`${getHeader('type')}: `)
        pdf.text(analysis.contractType, margin + typeWidth, yPosition)
        yPosition += 8
      }
      
      // SUMMARY
      yPosition += 5
      addText(getHeader('summary'), 14, true, [249, 115, 22])
      addLine([254, 243, 199])
      yPosition += 2
      addText(analysis.summary, 11, false, [51, 51, 51])
      yPosition += 10
      
      // RED FLAGS
      if (analysis.redFlags && analysis.redFlags.length > 0) {
        yPosition += 5
        addText(getHeader('redFlags'), 14, true, [220, 38, 38])
        addLine([254, 226, 226])
        yPosition += 2
        
        for (const flag of analysis.redFlags) {
          checkPageBreak(40)
          
          // Flag box background
          const boxStartY = yPosition
          pdf.setFillColor(254, 242, 242)
          
          // Calculate box height
          const titleLines = pdf.splitTextToSize(`${flag.category} - ${flag.severity.toUpperCase()}`, maxLineWidth - 4)
          const issueLines = pdf.splitTextToSize(flag.issue, maxLineWidth - 4)
          const explanationLines = pdf.splitTextToSize(flag.explanation, maxLineWidth - 4)
          const recLines = flag.recommendation ? pdf.splitTextToSize(`${getHeader('recommendation')}: ${flag.recommendation}`, maxLineWidth - 8) : []
          
          const boxHeight = (titleLines.length * 5.5) + (issueLines.length * 5.5) + (explanationLines.length * 4.5) + 
                           (recLines.length > 0 ? (recLines.length * 4.5) + 8 : 0) + 10
          
          if (yPosition + boxHeight > pageHeight - margin) {
            pdf.addPage()
            yPosition = margin
          }
          
          pdf.rect(margin, yPosition, contentWidth, boxHeight, 'F')
          pdf.setDrawColor(220, 38, 38)
          pdf.setLineWidth(1)
          pdf.line(margin, yPosition, margin, yPosition + boxHeight)
          
          yPosition += 5
          
          // Title
          pdf.setTextColor(220, 38, 38)
          pdf.setFontSize(11)
          pdf.setFont('helvetica', 'bold')
          for (const line of titleLines) {
            pdf.text(line, margin + 2, yPosition)
            yPosition += 5.5
          }
          
          // Issue
          pdf.setTextColor(51, 51, 51)
          pdf.setFont('helvetica', 'bold')
          for (const line of issueLines) {
            pdf.text(line, margin + 2, yPosition)
            yPosition += 5.5
          }
          
          // Explanation
          pdf.setTextColor(102, 102, 102)
          pdf.setFontSize(10)
          pdf.setFont('helvetica', 'normal')
          for (const line of explanationLines) {
            pdf.text(line, margin + 2, yPosition)
            yPosition += 4.5
          }
          
          // Recommendation
          if (flag.recommendation) {
            yPosition += 3
            pdf.setFillColor(255, 255, 255)
            pdf.roundedRect(margin + 2, yPosition - 3, contentWidth - 4, (recLines.length * 4.5) + 4, 2, 2, 'F')
            
            pdf.setTextColor(51, 51, 51)
            pdf.setFontSize(10)
            for (const line of recLines) {
              pdf.text(line, margin + 4, yPosition)
              yPosition += 4.5
            }
            yPosition += 3
          }
          
          yPosition += 5
        }
        
        yPosition += 5
      }
      
      // POSITIVE POINTS
      if (analysis.positivePoints && analysis.positivePoints.length > 0) {
        checkPageBreak(20)
        yPosition += 5
        addText(getHeader('positivePoints'), 14, true, [5, 150, 105])
        addLine([209, 250, 229])
        yPosition += 2
        
        pdf.setTextColor(51, 51, 51)
        pdf.setFontSize(11)
        pdf.setFont('helvetica', 'normal')
        
        for (const point of analysis.positivePoints) {
          const lines = pdf.splitTextToSize(point, maxLineWidth - 8)
          checkPageBreak(lines.length * 5.5 + 3)
          
          // Checkmark
          pdf.setTextColor(5, 150, 105)
          pdf.setFont('helvetica', 'bold')
          pdf.text('✓', margin, yPosition)
          
          // Point text
          pdf.setTextColor(51, 51, 51)
          pdf.setFont('helvetica', 'normal')
          for (const line of lines) {
            pdf.text(line, margin + 8, yPosition)
            yPosition += 5.5
          }
          yPosition += 2
        }
        
        yPosition += 5
      }
      
      // RECOMMENDATIONS
      if (analysis.recommendations && analysis.recommendations.length > 0) {
        checkPageBreak(20)
        yPosition += 5
        addText(getHeader('recommendations'), 14, true, [249, 115, 22])
        addLine([254, 243, 199])
        yPosition += 2
        
        pdf.setTextColor(51, 51, 51)
        pdf.setFontSize(11)
        pdf.setFont('helvetica', 'normal')
        
        for (let i = 0; i < analysis.recommendations.length; i++) {
          const lines = pdf.splitTextToSize(`${i + 1}. ${analysis.recommendations[i]}`, maxLineWidth - 5)
          checkPageBreak(lines.length * 6 + 3)
          
          for (const line of lines) {
            pdf.text(line, margin, yPosition)
            yPosition += 6
          }
          yPosition += 2
        }
      }
      
      // FOOTER
      const footerY = pageHeight - margin - 10
      pdf.setFontSize(9)
      pdf.setTextColor(150, 150, 150)
      pdf.setFont('helvetica', 'normal')
      
      const totalPages = (pdf as any).internal.getNumberOfPages()
      for (let i = 1; i <= totalPages; i++) {
        pdf.setPage(i)
        pdf.line(margin, footerY, pageWidth - margin, footerY)
        pdf.text(getHeader('footer1'), pageWidth / 2, footerY + 5, { align: 'center' })
        pdf.text(getHeader('footer2'), pageWidth / 2, footerY + 9, { align: 'center' })
        pdf.setFontSize(8)
        pdf.text(`${i} / ${totalPages}`, pageWidth - margin, footerY + 5, { align: 'right' })
      }
      
      const filename = `contract-analysis-${new Date().toISOString().split('T')[0]}.pdf`
      pdf.save(filename)
      
    } catch (error) {
      console.error('PDF generation error:', error)
      const errorMsg = language === 'nl' 
        ? 'Er ging iets mis bij het maken van de PDF. Probeer het opnieuw.'
        : language === 'fr'
        ? 'Une erreur s\'est produite lors de la création du PDF. Réessayez.'
        : 'Something went wrong creating the PDF. Please try again.'
      alert(errorMsg)
    }
  }
  
  return (
    <button
      onClick={exportToPdf}
      className="flex items-center gap-2 px-4 py-2 bg-orange-500 hover:bg-orange-600 text-white rounded-lg font-semibold transition-colors"
    >
      <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
      </svg>
      {t('results.downloadPdf')}
    </button>
  )
}
